from selenium.webdriver.common.by import By

from_field = (By.ID, 'from')
to_field = (By.ID, 'to')
taxi_button = (By.CSS_SELECTOR, 'button.button.round')
select_comfort = (By.XPATH, '//div[@class="tcard-title" and text()="Comfort"]')
phone_number_button = (By.CLASS_NAME, 'np-text')
phone_number_field = (By.ID, 'phone')
phone_next_button = (By.XPATH, '//div[@class="modal"]//button[@class="button full"]')
confirmation_code = (By.ID, 'code')
confirmation_button = (By.XPATH, '(//div[@class="modal"]//div[@class="section active"]//button[@class="button full"])[1]')
add_payment_method = (By.CLASS_NAME, 'pp-text')
add_card = (By.XPATH, '(//div[@class="pp-title"])[2]')
card_number_field = (By.ID, 'number')
cvv_number_field = (By.XPATH, '//input[@name="code"]')
unfocus_element = (By.CLASS_NAME, 'plc')
link_button = (By.XPATH, '(//div[@class="pp-buttons"]//button[@class="button full"])[1]')
card_added_checkmark = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/div[2]/div[3]/div[3]/label/span')
payment_close_button = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/button')
controller_message = (By.ID, 'comment')
order_a_blanket = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/span')
icecream_counter = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[3]')
icecream_number = (By.XPATH, '//div[@class="counter-value" and text()="2"]')
order_taxi_button = (By.XPATH, '//*[@id="root"]/div/div[3]/div[4]/button')
driver_modal = (By.XPATH, '//*[@id="root"]/div/div[5]/div[2]')
